### ISSUE TITLE
Regenerate paper results

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#101]
1. Fig4: arc graph (see issue #91 )
1. Figures 6 to 8
1. Tests for functions of undirected graphs (see network.py)

**Comment by prasadtalasila** [comment]
Pending work:    
Fig 4 ---> community hash to name conversion     
Fig 6(a) and (b) ---> community chosen is incorrect    
Fig 7 ---> distinction between channels and users    
Fig 8 ---> uniform color for vertices of one channel

**Comment by prasadtalasila** [comment]
Pending work as of 2-Sep-2017:

Fig 6(a) and (b) ---> community chosen is incorrect; the community membership and code length to be put in log files. The code length data goes into Tables 5 and 6 of the paper.    
Fig 7(b) ---> top-100 user-user copresence graph with communities labeled (taking too long to generate)    
Fig 8 ---> community chosen is incorrect; the community membership and code length to be put in log files.

**Comment by prasadtalasila** [comment]
@krishnacharya @kaushik-rohit please create / edit a bullet list of pending work on this issue. Thanks.

**Comment by kaushik-rohit** [comment]
1. Degree analysis log plots for node vs degree (In progress)
2. Conversation characteristics and cut off (In progress)
3. Integrating slackware analysis (In progress)
4. Integrating scummVM analysis (Todo)
5. Iteration issue for multi-channel analysis (Todo)

**Comment by rohangoel96** [comment]
@kaushik-rohit please update if 1,2,3 have been completed? Also I guess scummvm works as a seperate branch and it just needs to integrated into one branch?
Regarding 5) I hope the yesterday's mail solves it for you?

**Comment by prasadtalasila** [comment]
@rohangoel96 Item-2 is closed and item - 1 is close to completion (PR #140). Item - 3 is being worked on by @krishnacharya. It would be good if you can work on item - 5 and #134.

**Comment by rohangoel96** [comment]
@prasadtalasila item 5 completed via: a1d754a546eecd2e736b422eff702e37e4d39a12 . Sample Output for 5 days and 0 cutoff:
![message-2013-1-1-multi-cutoff](https://user-images.githubusercontent.com/8400677/30785494-b856d0d8-a167-11e7-923c-06c5c2319c9a.png)
Regarding #134, as far as I understand the problem, you cannot iterate over different cutoffs (by changing it like config.CUTOFF in sample.py) since config is just a file and by using config.CUTOFF=X  you aren't changing the value in the file. So that might be the reason of the problem mentioned in #134

**Comment by rohangoel96** [comment]
@kaushik-rohit please close this when you think it's complete.

**Comment by prasadtalasila** [comment]
We are still quite far from complete status. Assuming that all the pushed work results in proper analysis for Ubuntu channels, the pending work is as follows.

1. Add new code for scummvm and slackware channels
1. Add new code for correlation analysis

**Comment by kaushik-rohit** [comment]
@rohangoel96 @prasadtalasila I ran the complete analysis yesterday and the ubuntu script is working fine. I will now work on the slackware integration.
What is the second task about?

**Comment by prasadtalasila** [comment]
@kaushik-rohit please zip all the result, place them in drive/dropbox and send me email of all the link.

The details on the second task are given in the email discussion thread named **TODO list for paper revision**.

**Comment by rohangoel96** [comment]
Follow up: #168

**Comment by prasadtalasila** [comment]
work complete with b2dffdc.
