### ISSUE TITLE
Clean Directory Structure

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#11]
The present directory structure is very cumbersome and needs to be cleaned. Presently `.out` files too are included in the root directory which is very unpleasing. Scripts like `parser-ResponseTime_CDF.py` should be in the `lib` folder and correspondingly `Parser.py` and `TestingScript.py` should be edited to make library function for that particular script.

Ideally, the directory structure should be like https://github.com/rohangoel96/IRCLogParser and maybe one more folder named outputs where all the `.txt` and `.out` files are copied. 

I suppose the scripts I have worked upon are properly arranged now. @dhruvshekhawat, please arrange yours too.

**Comment by dhruvshekhawat** [comment]
Done. Thanks for pointing out :+1:
