### ISSUE TITLE
use nltk corpora for stopwords/common_english_words

### ISSUE THREAD

**Issue by kaushik-rohit** [prasadtalasila/IRCLogParser#132]
Using nltk corpora is more valuable so we wish to replace the custom list with nltk stopwords corpora.

**Comment by kaushik-rohit** [comment]
@prasadtalasila Currently we are using stop words from scikit-learn https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/feature_extraction/stop_words.py and we have two lists stored in python files under ext 1) extend_stop_words.py 2)common_english_words.py. We form a new corpora by taking union of all these. Should i include nltk corpora which has 152 stop words?
Some Obeservation
1) Nltk has 153 stop words. Scikit-learn has 318. common_english_words.py has 1000.
2) Out of 318 scikit stop words 217 are already in the common_english_words.
3) union of nltk and scikit corpora gives us 352 words. So nltk corpora has 34 words which are different from scikit.

**Comment by prasadtalasila** [comment]
@kaushik-rohit The present arrangement of using a union of scikit-learn and common english words seems satisfactory to me. Can you point to the location in the code where a union of two of these lists is being performed to create a new stop word list?

**Comment by kaushik-rohit** [comment]
@prasadtalasila the extended_stop_words function does this. Here https://github.com/prasadtalasila/IRCLogParser/blob/dev/lib/analysis/user.py#L414.

The above function is being used in keywords and clustering:
ex - https://github.com/prasadtalasila/IRCLogParser/blob/dev/lib/analysis/user.py#L242

**Comment by prasadtalasila** [comment]
sounds good. Nothing further to do on this task.
