### ISSUE TITLE
need for initial_row_filter in functions of vis.py module

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#141]
The following functions of vis.py module uses a parameter named initial_row_filter.

```python
exponential_curve_fit_and_plot(data, initial_rows_filter, output_directory, output_file_name)
generate_probability_distribution(data, initial_rows_filter)
```

These functions select the top-rows based on the value of initial_rows_filter. Given percentile cutoff, different channels and variable time periods, how do we pre-compute the number?

@rohangoel96 please provide clarification on this issue.

**Comment by rohangoel96** [comment]
`initial_row_filter` is used to select the number of rows on which the plotting has to be performed (the values for cl/rt dies out to zero very soon). It was observed that there were rarely any values of significance after row number 20, so we skip the rows after that from visualization.
If we want to compute it automatically and not hardcode 20 for making the library more general, we could probably start ignoring values once there enough of zero entries continuously. We also take care that there might be some outliers sometimes for example:
1 5
2 4
3 4
.
.
.
15 1
16 1
17 1
18 0
19 0
20 0
.
.
. 0 for all values
.
72 1 (as an outlier)
.
. 0 for all values here

**Comment by prasadtalasila** [comment]
We are already using PERCENTILE cutoff remove the insignificant values. That work is being done in channel.py. It would be better to visualize the given table (truncated by PERCENTILE or otherwise) in vis.py.

@kaushik-rohit please remove the `initial_row_filter` from both the above mentioned functions. Do put in the unit tests for these two functions.
