### ISSUE TITLE
heatmaps: plot not correct.

### ISSUE THREAD

**Issue by kaushik-rohit** [prasadtalasila/IRCLogParser#151]
Regenerate heatmaps on monthly basis for kubuntu-devel

**Comment by prasadtalasila** [comment]
Looks like PR #159 solves this problem. If so, @kaushik-rohit close this issue and move it to done on the project board.

**Comment by kaushik-rohit** [comment]
@prasadtalasila No, this is a separate issue. The current heatmaps comes out on daily basis (one column means one day, we want one column to represent one month).

**Comment by prasadtalasila** [comment]
If we can give a csv file to heatmap to generate the required visualization, we are happy for now.  The [line-117](https://github.com/prasadtalasila/IRCLogParser/blob/dev/ubuntu.py#L117) of ubuntu.py indicates a flexibility of using a user-provided heatmap.csv file to generate the visualization.

This issue can wait till the paper is done.

**Comment by prasadtalasila** [comment]
Looks like the dev branch already has the heatmap correctly generated in both csv and pdf formats. @kaushik-rohit, can we close this issue?

**Comment by prasadtalasila** [comment]
Not a priority right now.
