### ISSUE TITLE
arc_graph: add a config variable for output directory

### ISSUE THREAD

**Issue by kaushik-rohit** [prasadtalasila/IRCLogParser#152]
Store arc graph in the output_directory mentioned in config.py

**Comment by kaushik-rohit** [comment]
@prasadtalasila From what I can understand the save_js function just creates the .js file and the other html and ex.css should be present in the directory. In this case we cannot allow custom directory.

**Comment by prasadtalasila** [comment]
If the html and css remain static, then we can copy them from lib into a configured location in the ouput directory. The dynamically generated js file can be placed there as well.

**Comment by prasadtalasila** [comment]
Looks like we are placing the required js file with data into [protovis](https://github.com/prasadtalasila/IRCLogParser/tree/dev/lib/protovis) directory. Instead, we can copy the protovis directory to output directory and place the generated js file there.

**Comment by kaushik-rohit** [comment]
@prasadtalasila fixed in latest commit. Can be merged now.
