### ISSUE TITLE
Error while generating multi-channel-message-exchange

### ISSUE THREAD

**Issue by kaushik-rohit** [prasadtalasila/IRCLogParser#156]
`Building graph object with EDGE WEIGHT THRESHOLD: 0
========> 30 on 5000 conversations
[[1, 'jussi', 'yofel'], [17, 'shadeslayer_', 'ScottK'], [6, 'Tm_T', 'shadeslayer_'], [4, 'shadeslayer_', 'Tm_T'], [14, 'yofel', 'ScottK'], [12, 'ScottK', 'shadeslayer_'], [4, 'shadeslayer_', 'jtechidna'], [18, 'ScottK', 'yofel'], [2, 'shadeslayer_', 'SteveRiley_'], [122, 'shadeslayer_', 'yofel'], [89, 'yofel', 'shadeslayer_'], [24, 'Quintasan_', 'shadeslayer_'], [22, 'shadeslayer_', 'Quintasan_'], [9, 'mikhas', 'Quintasan_'], [12, 'Quintasan_', 'mikhas'], [7, 'Quintasan_', 'ScottK'], [1, 'yofel', 'Quintasan_'], [6, 'Quintasan_', 'yofel'], [1, 'shadeslayer_', 'mikhas'], [5, 'ubottu', 'Quintasan_'], [1, 'Quintasan_', 'kubotu'], [3, 'ScottKTraceback (most recent call last):
  File "ubuntu.py", line 123, in <module>
', 'Quintasan_'], [7, 'Noskcaj', 'ScottK'], [6, 'ScottK', 'Noskcaj'], [23, 'Riddell', 'yofel'], [10, 'ScottK', 'Riddell'], [2, 'jussi', 'soee'], [6, 'shadeslayer_', 'soee'], [3, 'soee', 'shadeslayer_'], [2, 'soee', 'yofel']]
Generating message-2013-1-1-cutoff-0.net
    msg_graph, msg_membership = community.infomap_igraph(ig_graph=None, net_file_location= output_directory + '"message-" + starting_date + "-cutoff-" + str(cutoff)' + '.net')
  File "/home/irclogparser/IRCLogParser/lib/analysis/community.py", line 26, in infomap_igraph
    ig_graph = igraph.read(net_file_location, format="pajek")
  File "/usr/local/lib/python2.7/dist-packages/igraph/__init__.py", line 4063, in read
    return Graph.Read(filename, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/igraph/__init__.py", line 2223, in Read
    return reader(f, *args, **kwds)
IOError: [Errno 2] No such file or directory: '/home/irclogparser/results/"message-" + starting_date + "-cutoff-" + str(cutoff).net'
`

**Comment by rohangoel96** [comment]
as far as I understand, @kaushik-rohit this is not an error. In multi-channel-message-exchange you are first storing a net file and then reading it. I think the file names for each of them are different hence the error. Btw you can also do this without saving the .net file and directly passing the graphs.
