### ISSUE TITLE
Replace plotly

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#170]
Free API key on plotly limits to only 100 uses per day (https://travis-ci.org/prasadtalasila/IRCLogParser/builds/283071557#L6576). Since buying an account on plotly is not feasible pltly should be replaced with something else. Other problems associated with plotly is that we require internet connection to be able to use plotly and hence use vis module from irclogparser. Moreover the online API calls makes the analysis slower. It will be better to have something working offline.

**Comment by prasadtalasila** [comment]
Perhaps the open source versions of [plot.ly](https://github.com/plotly/plotly.py), [plotly.js](https://github.com/plotly/plotly.js) and [dash](https://github.com/plotly/dash) would solve the problem.

**Comment by prasadtalasila** [comment]
@rohangoel96 @kaushik-rohit 
I have purchased plot.ly student license that allows us to generate results. We can now generate up to 1000 images per day. Once the plot.ly credentials are moved out of config.py (issue #187) and into a config file or environment variable, we can use the license even on travis.

**Comment by prasadtalasila** [comment]
This is for future.
