### ISSUE TITLE
Profiling required on presence methods

### ISSUE THREAD

**Issue by kaushik-rohit** [prasadtalasila/IRCLogParser#171]
The following function requires memory and time profiling.
1) network.channel_user_presence_graph_and_csv
2) community.infomap_igraph
3) vis.plot_infomap_igraph
4) network.degree_analysis_on_graph
5) vis.generate_log_plots

**Comment by prasadtalasila** [comment]
Please see the notes on [refactoring](https://github.com/prasadtalasila/IRCLogParser/wiki/Refactoring-Suggestions) wiki page.

**Comment by prasadtalasila** [comment]
Not a priority right now.
