### ISSUE TITLE
runtime errors on slackware code

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#172]
The slackware code as it exists on the **switch** branch on the server gives the following run-time error.
```
/home/irclogparser/IRCLogParser/lib/util.py:67: RuntimeWarning:
overflow encountered in exp
```
The function on that line is as follows.
```python
def exponential_curve_func(x, a, b, c):
    return a * np.exp(-b * x) + c
```
The line containing return statement is throwing up an overflow error.

A point to note: the code execution is super slow even for a single month.

**Comment by prasadtalasila** [comment]
I see the overflow error for two date ranges so far: 1 to 10 Jan 2013 and 1 to 30 Jan 2013. But the computation proceeds further and gives the results.

**Comment by rohangoel96** [comment]
@prasadtalasila @kaushik-rohit  regading the warning: https://stackoverflow.com/questions/4359959/overflow-in-exp-in-scipy-numpy-in-python

**Comment by kaushik-rohit** [comment]
@prasadtalasila The error seems to be because of overflow in the number of decimal points supported by default type in numpy. We can either manually set this to dtype=float128 at time of creating the array x and y or we can normalize the data values beforehand.

**Comment by prasadtalasila** [comment]
dtype=float128 seems to be a better suggestion. Normalization is not a good idea for comparison of a,b,c,MSE values for different message graphs. Please make the required modifications and open a PR on the existing dev branch.

**Comment by kaushik-rohit** [comment]
@prasadtalasila It seems we cannot directly cast the data to float128.
 `TypeError: Cannot cast array data from dtype('float128') to dtype('float64') according to the rule safe.`
In any case, this is not an error but a warning that we lose some precision for the calculated fit parameter. Do we actually want 128 floating precision?

**Comment by prasadtalasila** [comment]
Seems like this warning exists for analysis of all communities. Let's not get into 128 bit precision business now. I am closing this.
