### ISSUE TITLE
Move util functions from channel.py to util.py

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#176]
Move the truncate_table() and build_stat_dist() functions from channel.py to util.py. They truly belong to util.py module.

**Comment by rohangoel96** [comment]
Also TODO: rename plot_data to plot_lineat_data https://github.com/prasadtalasila/IRCLogParser/blob/dev/lib/vis.py#L25

**Comment by prasadtalasila** [comment]
Not a priority right now.
