### ISSUE TITLE
move config to top-level

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#178]
The configuration is to be moved to top-level so that it becomes easy to specify. Having one global config file would also make it easy to run analysis on multiple communities. 

With the present setup, running analysis on different communities like slackware and ubuntu is proving troublesome. Some of the python files are using config module like community and user, These files are also common for ubuntu and slack since they don't require parsing changes but when doing a slack analysis these should use the config in slack which is currently not specified.

I think we should do this before completely moving to config dictionary object.

**Comment by prasadtalasila** [comment]
I see quite a bit of scope for introducing concurrency into the project. For concurrency, the best way to pass configuration is via function parameters. From the concurrency perspecitve, the sooner we get to config object, the better it is.

**Comment by prasadtalasila** [comment]
For now, the only active configuration changes we are making in lib/slack/config.py vis-a-vis lib/config.py are the date range and I/O directories. In slack.py / slack-gc.py, we are fiddling with config.CUTOFF_PERCENTILE and config.THRESHOLD_MESSAGE_NUMBER_GRAPH. The functions that use these two config variables have already been moved to lib/slack directory. There fore, it looks safe for now.
@kaushik-rohit correct me if I am wrong in the above assessment.

But, this is a fault waiting to happen. It is better to fix the problem after the emergency work is done.

**Comment by kaushik-rohit** [comment]
@prasadtalasila Yes, after carefully looking at the modules, I see that the analysis won't be affected for now but this should be top priority work after we are done with paper related work.

**Comment by prasadtalasila** [comment]
Not a priority for now.
