### ISSUE TITLE
integrate test coverage into travis

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#191]
The test coverage tool needs to be integrated into travis

**Comment by prasadtalasila** [comment]
@kaushik-rohit we can use [coverage.py](https://coverage.readthedocs.io/en/coverage-4.4.1/) tool to create a test coverage report. See [stackoverflow](https://stackoverflow.com/questions/34728734/python-unit-test-coverage) for one possible solution.

Please also check out [z3c.coverage](https://pypi.python.org/pypi/z3c.coverage) to produce package specific coverage reports.

Once the coverage is generated successfully manually, the same command can be put in travis.yml.

**Comment by kaushik-rohit** [comment]
Below is the result of code coverage run.

Name                            Stmts   Miss  Cover   Missing
lib/analysis/channel.py           226    217     4%   25-160, 182-325, 341-351, 376-400
lib/analysis/community.py          61     61     0%   1-108
lib/analysis/network.py           450    106    76%   196-197, 201-215, 253-254, 259-264, 269-288, 374-382, 398-427, 514-520, 594, 740-789
lib/analysis/user.py              270     99    63%   81, 122-127, 131, 217-218, 264-267, 295-420
lib/in_out/reader.py               37      4    89%   45-46, 53-54
lib/in_out/saver.py                55     55     0%   1-129
lib/nickTracker.py                109      3    97%   98, 107, 157
lib/scummvm/nickTracker.py        109    109     0%   1-158
lib/slack/analysis/channel.py     226    226     0%   1-400
lib/slack/analysis/network.py     448    448     0%   1-787
lib/slack/in_out/reader.py         34     34     0%   1-69
lib/slack/nickTracker.py          109    109     0%   1-158
lib/slack/util.py                  95     95     0%   1-255
lib/util.py                        95     19    80%   67, 128-131, 221, 228-233, 242-244, 252-255
lib/validate.py                     6      6     0%   1-33
lib/vis.py                        213    213     0%   1-487
sample.py                          11     11     0%   1-11
scummvm.py                        144    144     0%   1-226
setup.py                           19     19     0%   1-25
slack-gc.py                       146    146     0%   1-230
slack.py                           71     71     0%   1-108
test/tests.py                     153     14    91%   40, 115-124, 132-137
ubuntu.py                         225    225     0%   1-303
TOTAL                            3312   2434    27%
