### ISSUE TITLE
refactor unit tests for lib/analysis/channel.py

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#201]
add ddt part

**Comment by prasadtalasila** [comment]
@Kausam any updates on this work?

**Comment by kaushik-rohit** [comment]
@prasadtalasila I am working on this issue. We haven't used ddt for unit-test but only for functional tests. They are already in functional-test directory with ddt format. Also the coverage for channel.py is 99% so all the code is being triggered, running it for more data(in ddt format) would only slow our build. Should I refactor this in ddt format?

**Comment by prasadtalasila** [comment]
@kaushik-rohit Lets not change this for now.
