### ISSUE TITLE
add unit tests for lib/analysis/community.py

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#202]

**Comment by Kausam** [comment]
I am working on this.

**Comment by Kausam** [comment]
I am working on this.

**Comment by prasadtalasila** [comment]
@Kausam any progress made on the unit tests?

**Comment by Kausam** [comment]
I discussed this with @kaushik-rohit and we have decided to move the function convert_id_name_community to the deprecated folder.

**Comment by prasadtalasila** [comment]
@Kausam Alright. Please send a PR to affect the change.

**Comment by kaushik-rohit** [comment]
Closing this, since the function was deprecated and the unit-testing for other function is already done.
