### ISSUE TITLE
add unit tests for lib/analysis/user.py

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#203]

**Comment by prasadtalasila** [comment]
PR #241 solves the issue.

**Comment by prasadtalasila** [comment]
@Kausam The code coverage on user.py [shows 78%](https://codecov.io/gh/prasadtalasila/IRCLogParser/src/dev/lib/analysis/user.py). Are you still working on this issue?

**Comment by Kausam** [comment]
@prasadtalasila Yes, I am working on this. Please check slack for details.
