### ISSUE TITLE
Networkx 1.11

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#21]
Some of the functions like `len` for `graph objects` have been deprecated in newer versions of networkx.
Need to re-write those functions in accordance with the updated version of nx.

Temporary Solution : Use networkx 1.8 (used by @dhruvshekhawat at the time of writing the code)
https://github.com/networkx/networkx/releases/tag/networkx-1.8.1

**Comment by rohangoel96** [comment]
@kaushik-rohit  this could be your first task. 
for your reference `len(L)` would create trouble in nx v1.11 here in
https://github.com/rohangoel96/IRCLogParser/blob/temp-branch/lib/AggregateGraph.py#L134

**Comment by kaushik-rohit** [comment]
@rohangoel96 we can use len (list(L)) in place of len (L)

**Comment by rohangoel96** [comment]
Closed via d18d1ebff12d397cd755f0db9a52add22973b3d9 and f2d819fbf72269a47916c2e752622e74829a9517
