### ISSUE TITLE
TODO: Update README.md

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#219]

**Comment by prasadtalasila** [comment]
@rohangoel96 Please specify the missing / outdated items so that they can be rectified and cross-checked.

**Comment by rohangoel96** [comment]
@prasadtalasila it seems to be updated right now. I just actually read a mail which I received a few days back (was incorrectly marked as spam) from a developer who across the repo and was enquiring about the same. He didn't see our dev branch and looking at the master, thought that we aren't working on the project so I just opened the issue. Now I see that recently dev was merged with master in the time between the mail being received and me reading it, so it's cool.
Closing the issue.

**Comment by prasadtalasila** [comment]
I can see a few points of improvement.

* Mentioning the [installation](https://github.com/prasadtalasila/IRCLogParser#installation) clearly in one / two sentences and then follow it up with shell commands. Also mention the approximate time that is likely to take to complete the installation process.
* License update to [GPL - 3.0](https://github.com/prasadtalasila/IRCLogParser#license)
* Spelling mistake in Generator under [Documentation](https://github.com/prasadtalasila/IRCLogParser#documentation) section. The word is spelt as *Genertor*
* Rewrite the text in Documentation section to the following.
```
IRCLogParser uses Sphinx Python Documentation Generator for generating documentation of the library.
The documentation is auto-generated from the commits made on the **dev** branch. The documentation corresponding to the latest commit on dev branch is hosted here.    
```
* Update the **Test** section with the correct commands for unit and integration tests. Also mention the approximate time that is likely to take to complete the tests.
* Change the order of the sections on README.md to Documentation, Installation, Testing, Usage.
* Remove the following sentence.    
```
Some of the visualisable sample outputs can be on the wiki, giving an idea about IRCLogParser's capabilites.
```
