### ISSUE TITLE
Installation Script

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#22]
Required: An Installation script to install all the dependencies in one go.

**Comment by rohangoel96** [comment]
@kaushik-rohit, since you'll be installing all the dependencies to start your work, this shoud be an easy task for you.

**Comment by kaivalyar** [comment]
Hi. I recently forked and set up the IRCLogParser on my computer. I had some trouble with getting the dependencies installed, however managed it later.

I was just wondering - would the installation script be in bash? if that is the case, I can just retrieve all the commands I ran on my terminal from my bash history, and produce a rudimentary installation script. Would that be helpful?

**Comment by rohangoel96** [comment]
Hi @kaivalyar, we are sorry for the trouble you went through for the installations and that is infact one of the primary reason we need this issue to be resolved asap so that future contributors do not face this problem.

Yes, a bash script would just serve the purpose. Something like https://gist.github.com/bgallagh3r/2853221 would be a great start.

Also, incase if you feel stuck anywhere else in the future please feel free to ping me anytime.

**Comment by rohangoel96** [comment]
Hi @kaivalyar, we are sorry for the trouble you went through for the installations and that is infact one of the primary reasons why we need this issue to be resolved asap; so that future contributors do not face this problem.

Yes, a bash script would just serve the purpose. Something like https://gist.github.com/bgallagh3r/2853221 would be a great start. I'd also suggest you to please work on the latest version of the repo and not the outdated one.

Also, incase if you feel stuck anywhere else in the future please feel free to ping me anytime.

**Comment by rohangoel96** [comment]
Hi @kaivalyar, we are sorry for the trouble you went through for the installations and that is infact one of the primary reasons why we need this issue to be resolved asap; so that future contributors do not face this problem.

Yes, a bash script would just serve the purpose. Something like https://gist.github.com/bgallagh3r/2853221 would be a great start. I'd also suggest you to please work on the latest version of the repo and not the outdated one.

Also, incase if you feel stuck anywhere else in the future please feel free to ping me anytime.

**Comment by kaivalyar** [comment]
The interesting thing I figured out while installing was that not only were the dependencies various python packages, but also non python Linux packages. I had to ```sudo apt-get install``` these. I don't think that these would be standard across all systems though. How would the installation script handle this though?

**Comment by rohangoel96** [comment]
@kaivalyar, though we presently only support ubuntu, but that's a valid point indeed.
you might want to take a look at this http://stackoverflow.com/questions/21421120/a-universal-bash-script-for-installing-with-apt-get-and-yum.

Moreover @kaushik-rohit is also working on this in my fork (https://github.com/rohangoel96/IRCLogParser/pull/1). It'll be great and a time-saver for all of us if both you could collaborate on the same.

**Comment by rohangoel96** [comment]
closed via 7a98242b2fe0a019611040186e9619c204c89108
