### ISSUE TITLE
Templates and labels for the project

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#231]
We need to have the following templates for the project contributors.

1. Issue template
1. Contributing guidelines template
1. Code of conduct template

We also need appropriate labels for issues and pull requests of the project. 

We can adopt and modify the basic templates and issue labels of the [autolabcli](https://github.com/AutolabJS/autolabcli) project.

**Comment by prasadtalasila** [comment]
Not a priority now.

**Comment by prasadtalasila** [comment]
@kaushik-rohit If you are done with the pending work, this issue might be worth looking into. 

We are going to use [coveralls](https://docs.coveralls.io/) to have reports on functional test coverage. Please add the same to travis.yml. Once the functional test reporting works, the README.md requires update as well to clearly show badges of unit tests and integration tests.

**Comment by kaushik-rohit** [comment]
@prasadtalasila Sir, I am working on the coveralls integration. Have you set the token to Travis?

**Comment by prasadtalasila** [comment]
@kaushik-rohit The PR #250 was reviewed and new badge given for coveralls integration. The coveralls does not require setting token on travis for public repositories.
