### ISSUE TITLE
Missing test reports in CodeClimate

### ISSUE THREAD

**Issue by bhuvangupta008** [prasadtalasila/IRCLogParser#244]
Code Climate is not showing up the test coverage report for lib/slack/ and lib/scummvm/nickTracker.py . The same are reported under coverage in travis build logs though.

**Comment by prasadtalasila** [comment]
That's because we ignored those paths in [codeclimate.yml](https://github.com/prasadtalasila/IRCLogParser/blob/master/.codeclimate.yml) config file.
