### ISSUE TITLE
Improvements to tests of nickTracker.py

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#254]
The nickTracker module exists at three places:
* [lib/nickTracker.py](https://codecov.io/gh/prasadtalasila/IRCLogParser/src/dev/lib/nickTracker.py)
* [lib/scummvm/nickTracker.py](https://codecov.io/gh/prasadtalasila/IRCLogParser/src/dev/lib/scummvm/nickTracker.py)
* [lib/slack/nickTracker.py](https://codecov.io/gh/prasadtalasila/IRCLogParser/src/dev/lib/slack/nickTracker.py)

There are three lines that are not covered by unit tests in these files. We need to add tests to cover these lines.

**Comment by bhuvangupta008** [comment]
- Modified log files for lib/nickTracker.py.
- For other two, since there are no different channels, we need to refactor the code to remove these uncovered redundant lines.

**Comment by prasadtalasila** [comment]
Issue solved via PR #265 and #266.
