### ISSUE TITLE
Automatically update Documentation post code change

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#27]
Presently, after every code change, to keep the code and documentation in sync it is required to run the command `make html` in `docs` directory so that the documentation updated

**Comment by prasadtalasila** [comment]
can travis-ci do this work for us? Seems possible looking at this [stackoverflow answer](http://stackoverflow.com/questions/23277391/how-to-publish-to-github-pages-from-travis-ci)

But the whole setup requires careful orchestration as security leaks seem very easy in this setup.

In the same vein, the github pages feature has been enabled for the project. Once done properly, the pages shall be available at http://prasadtalasila.github.io/IRCLogParser/.

**Comment by prasadtalasila** [comment]
we may also need a redirection page in docs/ directory in order to point to docs/build/html/index.html.

Since we are not merging the dev branch with master so often, we might be better off with having a separate gh-pages branch and use it as a base to serve the documentation.

**Comment by rohangoel96** [comment]
following from @prasadtalasila's last comment: the following command can help you deploy a certain folder to the gh-pages branch: `git subtree push --prefix docs/build/html/ origin gh-pages`

Also @prasadtalasila sir, since the permissions for travis and github pushing will require your access it'd be great if we can sit together some time and get this working. I can't set this up on my own without the owner access.

**Comment by rohangoel96** [comment]
@prasadtalasila I have the (updated) documentation setup on my local repo: http://rohangoel96.github.io/IRCLogParser which is just a redirection of `docs/build/html` but don't have the required permissions on your repo.

**Comment by prasadtalasila** [comment]
@rohangoel96 The API keys have been set and .travis.yml has been updated. We need a documentation update script along the lines of [auto-deploy](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd) or [steve's script](http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/).

Please cross-check the auto-deploy script first as it seems more up-to-date.

At present, there are two problems.

1. All builds including PRs try to update gh-pages
1. travis-ci deploy feature is not deploying properly.

Thus we need script to push to gh-pages.

**Comment by rohangoel96** [comment]
@prasadtalasila  thanks for the links. Since breaking your main branch and travis builds are considered a sin I have shifted the doc-automation to https://github.com/prasadtalasila/IRCLogParser/tree/docs-automation. The tut on https://gist.github.com/domenic/ec8b0fc8ab45f39403dd seems better as it doesn't require us to fiddle with npm. I guess it'll be better we can sit together and do this since it has many permission issues.

**Comment by rohangoel96** [comment]
thanks for the setup @prasadtalasila .
Since multiple commits for a single task isn't considered a good practice in open source I have squashed your commit into one. 030adca18ba560ba8daccb4832f70d64869429be

**Comment by rohangoel96** [comment]
Docs are now published correctly by travis:
dev : 3db6d8901073dd91fd26c479e62c6097f6385f97
gh-pages: f82eff9c26511113b661c50e4f5c39b62bf2e70a

**Comment by rohangoel96** [comment]
closed via https://github.com/prasadtalasila/IRCLogParser/pull/62

**Comment by prasadtalasila** [comment]
It may be desirable to delete the doc-automation and new-doc-automation branches.

**Comment by rohangoel96** [comment]
done

**Comment by prasadtalasila** [comment]
thanks @rohangoel96
