### ISSUE TITLE
list of methods for functional tests

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#295]
The methods / coding idioms we have in the driver files must be brought into the functional tests. Each test must correspond to one research result we are producing from the software.

**Comment by prasadtalasila** [comment]
The functional tests will try to reproduce the results reported in the [paper](https://www.dropbox.com/s/1jjr7lg58n7jpxe/IRCLogParser.pdf?dl=1). All the tests would be put in respective modules of test/functional-tests/ directory.

1. Dataset summary (dataset.py) ---> Table-I, pg 5 (27,28,83 and 87 of [slack.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/slack.py#L87))

1. Channel profile (channelprofile.py)
    * activity_graph ---> tabular form of figs 3(a) and 3(b)
    * conversation characteristics ---> Table-II, pg 9

1. Network profile
    * presence networks
        * CC
        * CU
        * UU
    * message exchange network
    * reduced networks
        * CC
        * CU
        * UU
        * message exchange network
        * message exchange network with arbitrary edge weight cutoff
    * degree distribution for CC, CU, UU and message exchange networks
        * Curve fits for degree distribution graphs
    * community analysis for CC, CU, UU and message exchange networks
        * Code length of Infomaps on different networks
    * message exchange network

1. User profile
    * user to channel graph.
    * user nick change graph.
    * keyword digest
    * HITS vs TF-IDF (Fig 11, pg 19)

**Comment by bhuvangupta008** [comment]
Channel profile (channelprofile.py)

* activity_graph ---> tabular form of figs 3(a) and 3(b) 
  * 27,28,34-38 of [slack.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/slack.py#L34-L38)
  * 121-125 of [ubuntu.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/ubuntu.py#L121-L125)
  * 24,25,31-35 of [scummvm.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/scummvm.py#L31-L35)
* conversation characteristics ---> Table-II, pg 9
  * 24,25,47-64 of [scummvm.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/scummvm.py#L47-L64)
  * 16-43 of [ubuntu.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/ubuntu.py#L16-L43)

**Comment by bhuvangupta008** [comment]
User profile

* user to channel graph.
  * lines 83-85 [ubuntu.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/ubuntu.py#L83-L85)
* user nick change graph.
  * (Couldn't find the ploting functions but this [line](https://github.com/prasadtalasila/IRCLogParser/blob/master/ubuntu.py#L135) of ubuntu.py makes an api call which then returns the users with same nicks) 
* keyword digest
  * lines 27,28,133 [slack.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/slack.py#L133)
  * lines 24,25,130 [scummvm.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/scummvm.py#L130)
  * lines 16,17,47 [ubuntu.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/ubuntu.py#L47)
* HITS vs TF-IDF (Fig 11, pg 19)

**Comment by bhuvangupta008** [comment]
Network profile

* presence networks
  * lines 83-85 [ubuntu.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/ubuntu.py#L83-L85)
* message exchange network
  * lines 27,28,83,89 of [slack.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/slack.py#L83)
  * lines 24,25,80,86 of [scummvm.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/scummvm.py#L80)
  * lines 16,17,20,22 of [ubuntu.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/ubuntu.py#L20-L22)
* reduced networks(incomplete)
  * lines 27,28,111,112 of [slack.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/slack.py#L111-L112)
  * lines 24,25,108,109 of [scummvm.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/scummvm.py#L108-L109)
  * lines 

* degree distribution for CC, CU, UU and message exchange networks
  * lines 83,84,85,98-118 of file [ubuntu.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/ubuntu.py#L98-L118)
  * lines 27,28,83,89-97 of files [slack.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/slack.py#L89-L97)
  * lines 24,25,80,86-94 of [scummvm.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/scummvm.py#L86-L94)
* community analysis for CC, CU, UU and message exchange networks
  * lines 187,188,196,197,204 of [slack.py](https://github.com/prasadtalasila/IRCLogParser/blob/dev/slack.py#L204)
  * lines 184,185,193,194,201 of [scummvm.py](https://github.com/prasadtalasila/IRCLogParser/blob/dev/scummvm.py#L201)
  *

**Comment by prasadtalasila** [comment]
work is complete.
