### ISSUE TITLE
Unexpected error messages thrown by reader module

### ISSUE THREAD

**Issue by Kausam** [prasadtalasila/IRCLogParser#308]
### Description

The reader module throws "Channel not found" errors when the log data availablity is not uniform across all dates under consideration and the `channel_list` is ` ["ALL"]` initially.

### Steps to Reproduce

1. In config.py, put `STARTING_DATE = '2013-01-01'`, `ENDING_DATE = '2013-01-02'` and `CHANNEL_NAME = ["ALL"]`
2. In `config.LOG_DIRECTORY + "2013/01/01"` put the files "#ubuntu.txt" and "#kubuntu.txt" only. In `config.LOG_DIRECTORY + "2013/01/02"` put a  single file: "#ubuntu.txt" file.
3. Run the driver program.

**Expected behavior:** No error message should be printed.

**Actual behavior:** A message like `[Error | io/linuxInput] Channel /home/irc_logs/ubuntu/2013/01/02/#kubuntu.txt doesn't exist` is printed to stdout

### Additional Information
The cause of the error is https://github.com/prasadtalasila/IRCLogParser/blob/dev/lib/in_out/reader.py#L64. Here, the `channel_list` passed as an argument to `check_if_path_and_file_is_valid` is directly taken from the previous iteration.
We want `channel_list` to be same at the beginning of every iteration.

**Comment by prasadtalasila** [comment]
PR #314 solves the issue.
