### ISSUE TITLE
functional tests for properties of network profile

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#312]
Create functional tests to verify the network profile. The suggested lines of code to be considered are:

Network profile
* degree distribution for CC, CU, UU and message exchange networks
  * lines 83,84,85,98-118 of file [ubuntu.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/ubuntu.py#L98-L118)
  * lines 20,27,28,83,89-97 of files [slack.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/slack.py#L89-L97)
  * lines 17, 24,25,80,86-94 of [scummvm.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/scummvm.py#L86-L94)
* community analysis for CC, CU, UU and message exchange networks
  * lines 187,188,196,197,204 of [slack.py](https://github.com/prasadtalasila/IRCLogParser/blob/dev/slack.py#L204)
  * lines 184,185,193,194,201 of [scummvm.py](https://github.com/prasadtalasila/IRCLogParser/blob/dev/scummvm.py#L201)
  * lines 73,89-96,161 of file [ubuntu.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/ubuntu.py#L89-L96)

**Comment by bhuvangupta008** [comment]
PR #319 solves this
