### ISSUE TITLE
Wrapper class for networkx

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#326]
A wrapper class networkx library using [Facade design pattern](https://en.wikipedia.org/wiki/Facade_pattern).

**Comment by bhuvangupta008** [comment]
Following methods are invoked of the networkx library:
- nx.Graph()
- nx.write_pajek
- nx.relabel_nodes
- networkx.algorithms.components.connected.connected_components
- nx.MultiDiGraph
- nx.DiGraph
- nx.hits
- networkx.readwrite.json_graph
- nx.nx.drawing.nx_agraph.to_agraph
- nx.is_isomorphic
- nx.read_pajek

**Comment by prasadtalasila** [comment]
nx.Graph()
nx.MultiDiGraph
nx.DiGraph

nx.relabel_nodes

networkx.algorithms.components.connected.connected_components
nx.is_isomorphic
nx.hits

nx.nx.drawing.nx_agraph.to_agraph

nx.read_pajek
nx.write_pajek
networkx.readwrite.json_graph

**Comment by prasadtalasila** [comment]
@bhuvangupta008 you can work on this issue.
