### ISSUE TITLE
Error in plotting some graphs

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#34]
TypeError: coercing to Unicode, need string or buffer, NoneType found for some graphs in the month of february

**Comment by prasadtalasila** [comment]
@rohangoel96 Please elaborate on the error. Specifically mention if the bug is still in the code base. If not, you can mention the commit that fixes this problem and close the issue.

**Comment by rohangoel96** [comment]
The error was occurring due to a nickname which had only escape characters. Was fixed. Fill try to find the commit and refer.
