### ISSUE TITLE
don't use max_expected variables

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#40]
conversation (https://github.com/prasadtalasila/IRCLogParser/blob/dev/lib/analysis/network.py#L31) should be dynamically filled up and there shouldn't any need to use "MAX_EXPECTED_DIFF_NICKS"

**Comment by rohangoel96** [comment]
similarily https://github.com/prasadtalasila/IRCLogParser/blob/dev/lib/nickTracker.py#L6

**Comment by prasadtalasila** [comment]
Use either queues or itertools to optimize append operations on lists of lists used for storing nicks.

**Comment by prasadtalasila** [comment]
Not a priority for now.
