### ISSUE TITLE
dependency management and packaging of the library

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#53]
we have a shell script based installation. If we can migrate the same to pip dependency management, we can overcome  potential version-based compatibility issues. The tutorial on the [fullstackpython](https://www.fullstackpython.com/application-dependencies.html) seems helpful.

Considering that our project is on Python 2, having [virtualenv](https://pypi.python.org/pypi/virtualenv) and [autoenv](https://github.com/kennethreitz/autoenv) seems worth the effort.

In the same vein, it would be good to have [pybuilder] integrated into the project which gets maven-like functionality into the project. Then a lot of heavy lifting that travis has to do goes away.

**Comment by prasadtalasila** [comment]
@kaushik-rohit if this work is complete, do close the issue.

**Comment by kaushik-rohit** [comment]
we still have to work on virtualenv integration and pybuilder.

**Comment by prasadtalasila** [comment]
We are moving the pip packaging to future.
