### ISSUE TITLE
TODO: Call Graphs

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#58]
https://github.com/gak/pycallgraph

**Comment by prasadtalasila** [comment]
a [stackoverflow answer](http://stackoverflow.com/questions/508277/is-there-a-good-dependency-analysis-tool-for-python?noredirect=1&lq=1) recommends [snakefood](http://furius.ca/snakefood/)

**Comment by rohangoel96** [comment]
@prasadtalasila  snakefood looks great. Thank you for the help sir.

**Comment by rohangoel96** [comment]
update: https://www.stack.nl/~dimitri/doxygen/manual/diagrams.html
- make sure to update the call graphs automatically (use travis?)

**Comment by prasadtalasila** [comment]
I tried out the pycallgraph. Here is the [gist](https://gist.github.com/prasadtalasila/71893b1eb8dfc425fba169b4c70b1475)

**Comment by prasadtalasila** [comment]
Here is a summary of [snakefood](https://gist.github.com/prasadtalasila/deb3e55d8f084ba375d1c31712e1c7e4) and a [sample graph](http://pasteboard.co/2ENQSGA5j.png) for our project.

**Comment by rohangoel96** [comment]
closed via 1e6252e28d4e59b5ccc32f76fdcc7fff125f36ac

**Comment by prasadtalasila** [comment]
The travis was changed and snakefood integration was lost. We need to bring it back.

**Comment by prasadtalasila** [comment]
Closed via PR #274.
