### ISSUE TITLE
make year of logs explicit

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#64]
At present, the command

    python module.py "nickChange" -f="1-1" -t="31-1"    

does not include the year of analysis. Including that would be useful in extending the analysis to long-range  logs.

**Comment by rohangoel96** [comment]
Thank you for pointing this @prasadtalasila sir.
That was actually used before the refactoring was done.
We now have config.py (which specifies complete date in format YYYY-MM-DD) to handle that.
https://github.com/prasadtalasila/IRCLogParser/blob/dev/lib/config.py#L4

We have tried to illustrate the use of the library in [sample.py](https://github.com/prasadtalasila/IRCLogParser/blob/dev/sample.py#L9)


Please close the issue if this is satisfying.

**Comment by prasadtalasila** [comment]
My bad. I was looking at the master branch. The present arrangement is good.
