### ISSUE TITLE
pre-release

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#65]
It would be a good practice to have a ready release / pre-release for the software. That way, any foreseen issues on the **dev** branch would not effect the people who would want to use the software.

We can have a working commit that is decent, create a release out of it. We can also upload the manually compiled documentation for that release.

**Comment by rohangoel96** [comment]
@prasadtalasila honestly that was exactly what I was planning when I cleaned the dev branch in my last commit. I am infact planning to set the IRCLogParser up on pip as well (http://peterdowns.com/posts/first-time-with-pypi.html). 

To do this, I am currently just waiting for @krishnacharya who is working on his PR #56 after which it will be a good idea to release a v1.0.0.

**Comment by prasadtalasila** [comment]
@rohangoel96 that's good news.

If I understand the situation correctly, right now one round of refactoring has been done. @krishnacharya is performing further refactoring to improve codeclimate score. If that is true, we can do the release now and perform incremental releases later on after significant improvements.

Unless @krishnacharya is fixing some bugs, waiting for him to improve the software is probably not going to be helpful in planning a release.
