### ISSUE TITLE
TODO: Profiler

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#67]
As suggested by @prasadtalasila, it will be a very good idea to use a [profiler](https://docs.python.org/2/library/profile.html) for our library. We could hence tweak the run-time performance for some heavy-load functions.

**Comment by prasadtalasila** [comment]
As suggested in #77, try vprof first. [vprof](https://github.com/nvdv/vprof) profiles the memory and execution time profiling of python code base. The package would be very useful in knowing the memory and execution time hogs in the IRCLogParser code base.

The tool does not require any new code development for profiling, but does require running on a desktop computer, ie, it does not run on travis.

**Comment by prasadtalasila** [comment]
Another profiling tool that I tried is [memory_profiler](https://github.com/fabianp/memory_profiler). This just gives the line-by-line memory consumption of a function. Very useful in our scenario of functions calling other functions.

Apart from this, some general advice I found, but yet to try - [1](http://pynash.org/2013/03/06/timing-and-profiling/), [2](https://www.huyng.com/posts/python-performance-analysis), [3](https://blog.ionelmc.ro/2013/06/08/python-profiling-tools/)

**Comment by prasadtalasila** [comment]
For the timing tests, [pytest-benchmark](https://github.com/ionelmc/pytest-benchmark) seems to be worthy solution. I tried it on another python project and it is giving time performance measurements. The documentation is a little patchy and I still can't figure out the fundamental difference between a run and an iteration. Otherwise, the package runs and gives meaningful results. See the pdf version of the document [here](https://media.readthedocs.org/pdf/pytest-benchmark/latest/pytest-benchmark.pdf).

**Comment by rohangoel96** [comment]
I tried both vprof and memory_profiler. Though the analysis of vprof is highly superior to that of memory_profiler, vprof is very time consuming and as @prasadtalasila  mentioned it can't work on travis (since the results are locally hosted over http).
memory_profiler's line by line analysis also takes ages to complete thus integrating it with travis would lead to builds running for hours. Hence I have integrated the overall memory_consumption_profiler which runs after each push and generates an image (graph) for the memory consumption.
See for example : https://clbin.com/eXMWPW.png generated by travis @ https://travis-ci.org/prasadtalasila/IRCLogParser/builds/220456378#L9678

I also tried to compare the images of those graphs but since running the same code for memory analysis at different time gives (a little) different results, failing builds on changing mem profiles is fruitless.

**Comment by rohangoel96** [comment]
pytest-benchmark can also be included separately along with memory usage analysis

Update: pytest-benchmark apparently works only with [pytest](https://docs.pytest.org/en/latest/) which we aren't using.

**Comment by rohangoel96** [comment]
@krishnacharya you had to try integration with pytest. Updates?

**Comment by prasadtalasila** [comment]
Not a priority now.
