### ISSUE TITLE
Better output formats

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#72]
We're currently using pickle to store the graphs for tests. Though it works just fine, the gpickle format is not human readable. It'll be better to use saving formats which are more human readable (pajek) so when we commit them on git, we can easily see the difference (`git diff`) and understand what kind of change was made to the graph.

**Comment by rohangoel96** [comment]
reference : https://github.com/prasadtalasila/IRCLogParser/pull/71/commits/414838e2206464b1180cfe17c8f4e00ea32d001f

**Comment by kaushik-rohit** [comment]
Yes. as we discussed earlier there is time gain with gpickle than pajek and hence we decided to go with gpickle. but i believe readability is definitely good to have.
I will fix this.

**Comment by prasadtalasila** [comment]
Not a priority now. Will be worked on in future.
