### ISSUE TITLE
Use Logging facility

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#74]
At present, the application is too verbose. Essentially we have two problems.
* All kinds of information printed on terminal
* Not adhering to UNIX philosophy of staying silent when there are no surprises.

Using the [logging](https://docs.python.org/2/library/logging.html) from standard library solves both the problems. We can specify different log levels and redirect the output to a log file instead of standard output.

**Comment by rohangoel96** [comment]
we were using a variable in config.py to enable/disbale logging until now (https://github.com/prasadtalasila/IRCLogParser/blob/master/IRCLogParser/lib/config.py#L1) but using logging from standard library is definitely a much better idea. Thanks !

**Comment by prasadtalasila** [comment]
Not a priority now. Will be worked on later.
