### ISSUE TITLE
code for CC graph generation - not in code base

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#91]
The code written for generating the arc diagram of the community-community (CC) network is not in the code base.

**Comment by krishnacharya** [comment]
To do:
-adjust to logarithmic weights for the CC adjacency matrix
-use d3

**Comment by prasadtalasila** [comment]
@krishnacharya please mention the PR that fixes this issue, close the issue and move it to done board.

**Comment by krishnacharya** [comment]
Implemented in PR #119
